---
abstract: 'Term::ReadLine style wrapper for Term::EditLine'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.9, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-ReadLine-EditLine
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Term::ReadLine::EditLine:
    file: lib/Term/ReadLine/EditLine.pm
    version: v1.1.1
requires:
  Term::EditLine: 0.05
  Term::ReadLine: 1.10
  perl: 5.008005
resources:
  bugtracker: https://github.com/tokuhirom/Term-ReadLine-EditLine/issues
  homepage: https://github.com/tokuhirom/Term-ReadLine-EditLine
  repository: git://github.com/tokuhirom/Term-ReadLine-EditLine.git
version: 1.1.1
x_contributors:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
  - 'tokuhirom <tokuhirom@gmail.com>'
